language: cpp
sudo: false
compiler:
  - gcc

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test

addons:
  apt:
    packages:
    - valgrind
script:
  - cmake .
  - make -j4
  - ctest
  - bash testValgrind.sh
